@startuml APTracker.Activity.GetDayInfo
skinparam DefaultFontSize 18
start
    :Найти существующий отчет на заданную дату;
    if (Существующий отчет найден) then (Истина)
        :Получить элементы отчета;
        :Получить элементы иерархии;
        :Для каждого элемента отчета отметить элементы иерархии;
        :Добавить данные отчета в ответ сервера;
    else (Ложь)
        :Найти первый предшествующий заданному дню отчетный день;

        if (Существующий отчет найден) then (Истина)
            :Получить элементы отчета за найденный день;
            :Получить элементы иерархии;
            :Для каждого элемента отчета отметить элементы иерархии;
        else (Ложь)
            :Получить иерархию в шаблон без обработки;
        endif
            :Добавить шаблон в ответ сервера;
    endif
    :Вернуть ответ сервера;
stop
@enduml