@startuml APTracker.Activity.GetBagReport
skinparam DefaultFontSize 18
start
partition "Формирование отчета по портфелю" {
    :Получить все элементы отчетов по расходам за период;
    :Получить всех клиентов заданного портфеля из элементов расходов;
    :Получить все проекты заданного портфеля из элементов расходов;
    :Получить все статьи заданного портфеля из элементов расходов;
    :Получить результаты по статьям;
    :Получить результаты по проектам;
    :Получить результаты по клиентам;
    :Объединить данные и отправить ответ;
}
stop
@enduml