@startuml 'APTracker Use Cases'
left to right direction
skinparam DefaultFontSize 18

:Администратор: as Admin
:Руководитель: as Manager
:Сотрудник: as Developer

Admin -|> Manager
Manager -|> Developer


(Управлять портфелями) as (BagManage)
(Просматривать портфели) as (BagView)
(Создать портфель) as (BagCreate)

(Управлять одним портфелем) as (BagManageSingle)
(Редактировать название портфеля) as (BagRename)
(Назначить ответственного портфеля) as (BagSetResponsive)

(Добавить статью в портфель) as (BagAddArticle)
(Перенести статью в портфель) as (BagMoveArticle)

(Добавить проект в портфель) as (BagAddProject)
(Перенести проект в портфель) as (BagMoveProject)

(Добавить заказчика в портфель) as (BagAddClient)
(Перенести заказчика в портфель) as (BagMoveClient)

(BagManage) <.. (BagCreate) : extends
(BagManage) ..> (BagView) : include

(BagManage) <.. (BagManageSingle) : extends

(BagManageSingle) <.. (BagAddArticle) : extends
(BagAddArticle) <.. (BagMoveArticle) : extends

(BagManageSingle) <.. (BagAddProject) : extends
(BagAddProject) <.. (BagMoveProject) : extends

(BagManageSingle) <.. (BagAddClient) : extends
(BagAddClient) <.. (BagMoveClient) : extends

(BagManageSingle) <.. (BagRename) : extends

(BagManageSingle) .> (BagSetResponsive) : extends

Admin --> (BagManage)

(Получить отчет уровня портфеля) as (GetBagReport)
Manager --> (GetBagReport)

(Заполнить отчет за день) as (FillDailyReport)
(Зафиксировать отчет за день) as (FixDailyReport)
(FillDailyReport) ..> (FixDailyReport) : extends

Developer --> (FillDailyReport)

(Управлять иерархией) as (ManageHierarchy)
(Просматривать иерархию) as (ViewHierarchy)
(ManageHierarchy) ..> (ViewHierarchy) : include

(Управлять клиентом) as (ManageClient)
(Управлять проектом клиента) as (ManageProject)
(Управлять статьей проекта) as (ManageArticle)

(ManageHierarchy) <.. (ManageClient) : extends
(ManageClient) <.. (ManageProject) : extends
(ManageProject) <.. (ManageArticle) : extends


(Добавить клиента) as (AddClient)
(Добавить проект клиенту) as (AddProject)
(Добавить статью проекту) as (AddArticle)

(ManageHierarchy) <.. (AddClient) : extends
(ManageClient) <.. (AddProject) : extends
(ManageProject) <.. (AddArticle) : extends

(Перенести проект клиенту) as (TransferProject)
(Перенести статью проекту) as (TransferArticle)

(ManageProject) <. (TransferProject) : extends
(ManageArticle) <. (TransferArticle) : extends

(Управлять общими статьями) as (ManageCommonArticles)

(ManageCommonArticles) ..> (ViewCommonArticles) : include

(ManageCommonArticles) <.. (AddCommonArticle) : extends
(ManageCommonArticles) <.. (EditCommonArticle) : extends

(Просматривать общие статьи) as (ViewCommonArticles)
(Добавить общую статью) as (AddCommonArticle)
(Редактировать общую статью) as (EditCommonArticle)

(Управлять сотрудниками) as (ManageUsers)

(Установить ставку сотруднику) as (SetUserRate)
(ManageUsers) <. (SetUserRate) : extends


Admin --> (ManageUsers)
Admin --> (ManageHierarchy)
Admin --> (ManageCommonArticles)

legend top left
    Для выполнения любого сценария,
    указанного в данной диаграмме,
    требуется аутентификация пользователя
endlegend


@enduml